# Generated by Django 5.0.1 on 2024-02-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
