# Generated by Django 5.0.1 on 2024-02-07 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_alter_company_details_alter_company_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField(max_length=10)),
                ("linkedin_profile", models.URLField()),
                ("personal_website", models.URLField()),
                ("personal_note", models.TextField()),
                ("resume", models.FileField(upload_to="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myApp.company"
                    ),
                ),
            ],
        ),
    ]
