# Generated by Django 5.0.1 on 2024-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_applicant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
